[package]
name = "wgpu-load-test"
version = "0.1.0"
authors = ["Alexis Andre <mactuitui+github@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.20"
wgpu = "0.5"
futures = "0.3.4"
bytemuck = "1.2.0"
cgmath = "0.17"

